training_set_kwargs:
G_kwargs:
  class_name: training.triplane.TriPlaneGenerator
  fused_modconv_default: inference_only
  z_dim: 512
  w_dim: 512
  num_fp16_res: 0
  architecture: skip
  channel_base: 32768 # 결구엔 chanels_max와 최소값을 비교하기 떄문에 channel_max로 결정된다고 보면됨
  channel_max: 512
  mapping_kwargs:
    num_layers: 2

  rendering_kwargs:
    image_resolution: null
    disparity_space_sampling: False
    clamp_mode: softplus
    superresolution_module: null
    c_gen_conditioning_zero: true
    gpc_reg_prob: 0.5
    c_scale: 1.0
    superresolution_noise_mode: random
    density_reg: 0.25
    density_reg_p_dist: 0.004
    reg_type: l1
    decoder_lr_mul: 1.0
    decoder_activation: sigmoid
    use_torgb_raw: false
    triplane_size: 256
    triplane_depth: 1
    avg_camera_radius: null
    avg_camera_pivot: null
    trans_reg: 0.0
    use_background: true
  sr_num_fp16_res: 4
  sr_kwargs:
    channel_base: 32768
    channel_max: 512
    fused_modconv_default: inference_only

G_opt_kwargs:
  class_name: torch.optim.Adam
  betas: [0,0.99]
  eps: 1e-8

D_kwargs:
  block_kwargs:
    freeze_layers: 0
  channel_base: 32768
  channel_max: 512
  class_name: training.dual_discriminator.MaskDualDiscriminator
  disc_c_noise: 0
  epilogue_kwargs:
    mbstd_group_size: 4
  mapping_kwargs: {}
  seg_channels: 1
  seg_resolution: 128


D_opt_kwargs:
  class_name: torch.optim.Adam
  betas: [0,0.99]
  eps: 1e-8
  lr: 0.002

loss_kwargs:
  class_name: training.loss.StyleGAN2Loss
  neural_rendering_resolution_initial: 64
  bcg_reg_prob: 0.2
  blur_fade_kimg: 200
  blur_init_sigma: 10
  density_noise_fade_kimg: 0
  dual_discrimination: true
  filter_mode: antialiased
  gpc_reg_fade_kimg: 1000
  gpc_reg_prob: 0.5
  neural_rendering_resolution_fade_kimg: 1000
  neural_rendering_resolution_final: 128
  neural_rendering_resolution_initial: 64
  r1_gamma: 1
  r1_gamma_seg: 1
  style_mixing_prob: 0


dataset_kwargs: # =training_set_kwargs
  class_name: training.dataset.MaskLabeledDataset
  img_path: testdata_img.zip
  seg_path: testdata_seg.zip
  use_labels: True
  max_size: None
  xflip: true
  min_yaw: 0
  max_yaw: 180
  back_repeat: 4 # 뒷머리 부분 얼마나 반복할지
  resolution:
  use_labels:
  max_size:


augment_kwargs:
  class_name: 'training.augment.AugmentPipe',
  xflip: 1,
  rotate90: 1,
  xint: 1,
  scale: 1,
  rotate: 1,
  aniso: 1,
  xfrac: 1,
  brightness: 1,
  contrast: 1,
  lumaflip: 1,
  hue: 1,
  saturation: 1

ada_kimg: 100
ada_target: 0.6

augment_p: 0.2
batch_gpu: 1
batch_size: 1
cudnn_benchmark: true
data_loader_kwargs:
  num_workers: 3
  pin_memory: true
  prefetch_factor: 2
ema_rampup: null
image_snapshot_ticks: 50
kimg_per_tick: 4

metrics: fid50k_full
network_snapshot_ticks: 50
num_gpus: 1
random_seed: 0
resume_kimg: 0
resume_pkl: null
total_kimg: 25000
training_set_kwargs:
  random_seed: 0
  use_labels: true
  xflip: false
